// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Playback position update (sent frequently during playback)
 */
export type PlaybackUpdate = { current_time: number, version: number, };
