// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Playback speed update (sent when user changes speed)
 */
export type PlaybackSpeedUpdate = { playback_speed: number, version: number, };
