// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Session state - the canonical shape for all session data.
 * Used by: ServerMessage::StateSync, client SyncState, localStorage, etc.
 */
export type SessionState = { current_time: number, playback_speed: number, volume: number, version: number, };
