// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Volume update (sent when user changes volume)
 */
export type VolumeUpdate = { volume: number, version: number, };
